
!obj:pylearn2.train.Train {
  dataset: !obj:pylearn2.sandbox.nlp.datasets.skipgram.H5Skipgram {
    path: '/data/lisatmp3/pougetj/double_filtered_binarized_corpus_train.h5',
    node: '/double_filtered_binarized_corpus_train',
    which_set: 'train',
    frame_length: &n 7,
    stop: 1000,
    _iter_num_batches: 100,
    X_labels: &l 15000,
    load_to_memory: True
  },
  model: !obj:pylearn2.models.mlp.MLP {
    input_space: !obj:pylearn2.space.IndexSpace {
      dim: 1,
      max_labels: *l  
    },
    target_source: ['target0', 'target1', 'target2', 'target3', 'target4', 'target5' ],
    layers: [
      !obj:pylearn2.sandbox.nlp.models.mlp.ProjectionLayer {
        layer_name: 'projection',
        dim: 512,
        irange: 0.01
      },
      !obj:pylearn2.models.mlp.Linear {
        layer_name: 'target_projection',
        dim: *l,
        irange: 0.01
      },
     !obj:pylearn2.models.mlp.CompositeLayer {
        layer_name: 'composite_layer',
        layers: 
        [!obj:pylearn2.sandbox.nlp.models.mlp.Softmax {
            n_classes: *l,
            layer_name: 'h0',
            irange: 0.01,
            no_affine: True
           # binary_target_dim: 1
          },
          !obj:pylearn2.sandbox.nlp.models.mlp.Softmax {
           n_classes: *l,
            layer_name: 'h1',
            irange: 0.01,
            no_affine: True
           # binary_target_dim: 1
          },
          !obj:pylearn2.sandbox.nlp.models.mlp.Softmax {
            n_classes: *l,
            layer_name: 'h2',
            irange: 0.01,
            no_affine: True
           # binary_target_dim: 1
          },
          !obj:pylearn2.sandbox.nlp.models.mlp.Softmax {
            n_classes: *l,
            layer_name: 'h3',
            irange: 0.01,
            no_affine: True
           # binary_target_dim: 1
          },
          !obj:pylearn2.sandbox.nlp.models.mlp.Softmax {
            n_classes: *l,
            layer_name: 'h4',
            irange: 0.01,
            no_affine: True
           # binary_target_dim: 1
          },
          !obj:pylearn2.sandbox.nlp.models.mlp.Softmax {
            n_classes: *l,
            layer_name: 'h5',
            irange: 0.01,
            no_affine: True
           # binary_target_dim: 1
          }
        ]
      }
    ],
  },
  algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
    batch_size: 32,
    learning_rate: .01,
    learning_rule: !obj:pylearn2.training_algorithms.learning_rule.AdaDelta {},
    monitoring_dataset: {
     'valid': !obj:pylearn2.sandbox.nlp.datasets.skipgram.H5Skipgram {
        path: '/data/lisatmp3/pougetj/double_filtered_binarized_corpus_valid.h5',
        node: '/double_filtered_binarized_corpus_valid',
        which_set: 'valid',
        frame_length: *n,
        stop: 100000,
        _iter_num_batches: 100,
        X_labels: *l,
        load_to_memory: True
      },
    },
  },
  save_freq: 1,
}
